name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort black==21.12b0 "click<8.0.0" 

      - name: Run isort check
        run: |
          isort . --check-only --diff

      - name: Run black check
        run: |
          black . --check --diff

      - name: Run flake8
        run: |
          flake8 .

    

